server:
  context-path: /labelPrint
  port: 8183
  session:
    timeout: -1
  tomcat:
    uri-encoding: utf-8
  applicationId: 827 
logging:
  level:
    com.bondex: debug
    org.springframework.jdbc: debug
filter: 
   stat: 
    log-slow-sql: true
spring:
  profiles:
    active: test
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
  freemarker:
    content-type: text/html; charset=utf-8
    cache: false
    template-loader-path:
      - classpath:/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    #########设置request，在页面获取request.getContextPath()############
    request-context-attribute: request
    allow-request-override: false
    allow-session-override: false
    prefer-file-system-access: true
    prefix: 
    suffix: .html
    charset: UTF-8
    enabled: true
    check-template-location: true
    order: 1
  application:
    name: printServer
  activemq:
    close-timeout: 
  messages:
    fallback-to-system-locale: 
  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+10
    locale: zh_CN
    ##前端JSON序列化null属性值不参与序列化
    default-property-inclusion: non-null 
    serialization:
       #格式化输出 
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
   
restTemplate:
  connectionRequestTimeout: 1000
  connectTimeout: 10000
  socketTimeout: 10000
  maxConnTotal: 10000
region:
  chengdu: xidun,jichang,xiqu
  qingdao: futai
